#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════════╗
║   Plant Disease Detection & Treatment Advisory                       ║
║   Multilingual · RAG-Powered · Accessible                            ║
╚══════════════════════════════════════════════════════════════════════╝

Hugging Face Space — app.py
Compatible with: Python 3.10+, Gradio 4.x
"""

# ─────────────────────── Standard Library ────────────────────────────────────
import os
import sys
import json
import time
import logging
import subprocess
import tempfile
import textwrap
from pathlib import Path
from typing import Optional, Tuple

# ─────────────────────── Third-Party Core ────────────────────────────────────
import gradio as gr
import torch
from PIL import Image

# ─────────────────────── Project Modules ─────────────────────────────────────
from translations import ui_translations, disease_info          # UI strings & disease taxonomy
from disease_id_mapping import disease_id_mapping               # Class → disease_id
from treatment_data import TREATMENT_DB                         # Inline treatment database

# Pre-translated cache — generated by generate_translations.py (run once on Kaggle/Colab GPU).
# When present, all Hindi/Urdu/Telugu text is served from this dict instantly,
# completely bypassing IndicTrans2 at runtime.
try:
    from treatment_data_translated import TRANSLATED_DB
    _CACHE_LOADED = True
except ImportError:
    TRANSLATED_DB  = {}
    _CACHE_LOADED  = False

# ─────────────────────── Logging Setup ───────────────────────────────────────
logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
log = logging.getLogger(__name__)

# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 1 — ENVIRONMENT & SECRETS
# ═════════════════════════════════════════════════════════════════════════════
HF_TOKEN       = os.environ.get("HF_TOKEN", "")
GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY", "")
CONFIDENCE_THRESHOLD = 50.0         # % threshold for "confident" prediction

# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 2 — LAZY MODEL LOADERS (only load when first needed)
# ═════════════════════════════════════════════════════════════════════════════

_yolo_v8  = None
_yolo_v12 = None
_indic_tokenizer = None
_indic_model     = None
_indic_processor = None
_rag_llm         = None
_rag_chain       = None
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

CLASS_NAMES = {
    0: "Apple__BlackRot",        1: "Apple__CedarRust",       2: "Apple__Healthy",
    3: "Apple__Scab",            4: "Corn__CommonRust",        5: "Corn__GrayLeafSpot",
    6: "Corn__Healthy",          7: "Corn__LeafBlight",        8: "Corn__NorthernLeafBlight",
    9: "Grape__BlackRot",        10: "Grape__Esca",            11: "Grape__Healthy",
    12: "Grape__LeafBlight",     13: "Potato__EarlyBlight",   14: "Potato__Healthy",
    15: "Potato__LateBlight",    16: "Tomato__BacterialSpot", 17: "Tomato__BacterialWilt",
    18: "Tomato__BrownSpots",    19: "Tomato__EarlyBlight",   20: "Tomato__Healthy",
    21: "Tomato__LateBlight",    22: "Tomato__LeafMold",       23: "Tomato__MosaicVirus",
    24: "Tomato__SeptoriaLeafSpot", 25: "Tomato__SpiderMites", 26: "Tomato__TargetSpot",
    27: "Tomato__YellowLeafCurlVirus",
}

# FLORES-200 codes for IndicTrans2
INDIC_LANG_CODES = {
    "Hindi":   "hin_Deva",
    "Urdu":    "urd_Arab",
    "Telugu":  "tel_Telu",
}

# edge-tts neural voices
TTS_VOICES = {
    "English": "en-US-JennyNeural",
    "Hindi":   "hi-IN-SwaraNeural",
    "Urdu":    "ur-PK-AsadNeural",
    "Telugu":  "te-IN-ShrutiNeural",
}



# Extra translation keys for disease details / treatment panels
EXTRA_T = {
    "English": {
        "pathogen_type":       "Pathogen Type",
        "symptoms":            "Symptoms",
        "field":               "Field",
        "detail":              "Detail",
        "chemical_mgmt":       "Chemical Management",
        "preventive_measures": "Preventive Measures",
        "disease_label":       "Disease",
        "crop_label":          "Crop",
        "best_local_match":    "Best local match (keyword search):",
        "no_match":            "No match found for the described symptoms. Please consult your nearest KVK or agricultural extension officer.",
        "symptom_placeholder": "e.g., yellow spots with dark borders on lower leaves…",
    },
    "Hindi": {
        "pathogen_type":       "रोगकारक प्रकार",
        "symptoms":            "लक्षण",
        "field":               "क्षेत्र",
        "detail":              "विवरण",
        "chemical_mgmt":       "रासायनिक प्रबंधन",
        "preventive_measures": "निवारक उपाय",
        "disease_label":       "बीमारी",
        "crop_label":          "फसल",
        "best_local_match":    "सबसे अच्छा स्थानीय मिलान (कीवर्ड खोज):",
        "no_match":            "वर्णित लक्षणों के लिए कोई मिलान नहीं मिला। कृपया अपने नजदीकी KVK या कृषि विस्तार अधिकारी से संपर्क करें।",
        "symptom_placeholder": "जैसे: पत्तियों पर पीले धब्बे, किनारे काले हैं… (हिंदी, English या Hinglish में लिखें)",
    },
    "Urdu": {
        "pathogen_type":       "روگزا قسم",
        "symptoms":            "علامات",
        "field":               "فیلڈ",
        "detail":              "تفصیل",
        "chemical_mgmt":       "کیمیائی انتظام",
        "preventive_measures": "احتیاطی تدابیر",
        "disease_label":       "بیماری",
        "crop_label":          "فصل",
        "best_local_match":    "بہترین مقامی میل (کلیدی لفظ تلاش):",
        "no_match":            "بیان کردہ علامات کے لیے کوئی میل نہیں ملا۔ براہ کرم اپنے قریبی KVK یا زرعی توسیعی افسر سے رابطہ کریں۔",
        "symptom_placeholder": "مثلاً: پتوں پر پیلے دھبے، سیاہ کنارے… (اردو یا English میں لکھیں)",
    },
    "Telugu": {
        "pathogen_type":       "వ్యాధికారక రకం",
        "symptoms":            "లక్షణాలు",
        "field":               "వివరణ",
        "detail":              "వివరాలు",
        "chemical_mgmt":       "రసాయన నిర్వహణ",
        "preventive_measures": "నివారణ చర్యలు",
        "disease_label":       "వ్యాధి",
        "crop_label":          "పంట",
        "best_local_match":    "అత్యుత్తమ స్థానిక సరిపోలిక (కీవర్డ్ శోధన):",
        "no_match":            "వివరించిన లక్షణాలకు సరిపోలిక కనుగొనబడలేదు. దయచేసి మీ సమీప KVK లేదా వ్యవసాయ విస్తరణ అధికారిని సంప్రదించండి.",
        "symptom_placeholder": "ఉదా: ఆకులపై పసుపు మచ్చలు, చీకటి అంచులు… (తెలుగు లేదా English లో రాయండి)",
    },
}

def _xt(lang: str, key: str) -> str:
    """Get extra translation key, fallback to English."""
    return EXTRA_T.get(lang, EXTRA_T["English"]).get(key, EXTRA_T["English"][key])

# ─── YOLO loader ─────────────────────────────────────────────────────────────
def _load_yolo_models():
    global _yolo_v8, _yolo_v12
    if _yolo_v8 is not None:
        return True
    try:
        from ultralytics import YOLO
        v8_path  = os.environ.get("YOLO_V8_PATH",  "models/finetuned_yolo8n.pt")
        v12_path = os.environ.get("YOLO_V12_PATH", "models/finetuned_yolo12n.pt")

        if not Path(v8_path).exists():
            log.warning(f"YOLOv8 weights not found at {v8_path}. Using base yolov8n.")
            v8_path = "yolov8n.pt"
        if not Path(v12_path).exists():
            log.warning(f"YOLOv12 weights not found at {v12_path}. Using base yolov8n as fallback.")
            v12_path = v8_path

        _yolo_v8  = YOLO(v8_path)
        _yolo_v12 = YOLO(v12_path)
        log.info("✅ YOLO models loaded successfully.")
        return True
    except Exception as e:
        log.error(f"❌ YOLO load failed: {e}")
        return False


# ─── IndicTrans2 loader ───────────────────────────────────────────────────────
def _load_indic_model():
    global _indic_tokenizer, _indic_model, _indic_processor
    if _indic_tokenizer is not None:
        return True
    try:
        # Install IndicTransToolkit at runtime to avoid HF Spaces init-phase
        # DNS failures that occur when pip tries to clone git packages during build.
        import importlib, subprocess, sys
        if importlib.util.find_spec("IndicTransToolkit") is None:
            log.info("⏳ Installing IndicTransToolkit (first run only)…")
            subprocess.check_call([
                sys.executable, "-m", "pip", "install", "--quiet",
                "git+https://github.com/VarunGumma/IndicTransToolkit.git"
            ])
            log.info("✅ IndicTransToolkit installed.")

        from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
        from IndicTransToolkit import IndicProcessor

        model_name = "ai4bharat/indictrans2-en-indic-dist-200M"
        log.info("⏳ Loading IndicTrans2 model (first run may take ~2 min)…")
        _indic_tokenizer  = AutoTokenizer.from_pretrained(
            model_name, trust_remote_code=True, token=HF_TOKEN or True
        )
        _indic_model = AutoModelForSeq2SeqLM.from_pretrained(
            model_name, trust_remote_code=True, token=HF_TOKEN or True
        ).to(DEVICE)
        _indic_processor = IndicProcessor(inference=True)
        log.info("✅ IndicTrans2 loaded.")
        return True
    except Exception as e:
        log.error(f"❌ IndicTrans2 load failed: {e}")
        return False


# ─── Gemini RAG loader ────────────────────────────────────────────────────────
def _load_rag_chain():
    global _rag_llm, _rag_chain
    if _rag_chain is not None:
        return True
    if not GOOGLE_API_KEY:
        log.warning("GOOGLE_API_KEY not set — RAG symptom search disabled.")
        return False
    try:
        from langchain_google_genai import ChatGoogleGenerativeAI
        from langchain_core.prompts import ChatPromptTemplate
        from langchain_core.output_parsers import StrOutputParser

        os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY
        _rag_llm = ChatGoogleGenerativeAI(temperature=0.2, model="gemini-2.0-flash")

        prompt = ChatPromptTemplate.from_template(
            """You are an expert Indian agricultural advisor.
            A farmer describes symptoms on their {crop} crop. Identify the most likely disease
            and give actionable treatment advice based on ICAR / TNAU / KVK recommendations.
            Be concise but practical.

            IMPORTANT: Respond in plain text only. Do NOT use any markdown, bold (**), italic (*),
            headers (#), or special formatting. Use plain numbered lists or dashes only.

            Crop: {crop}
            Symptoms described by farmer: {symptoms}

            Respond with:
            Disease: [name of disease]
            Crop: {crop}

            Immediate actions (within 24 hours):
            - [action]

            Chemical Management:
            - [product name, dose, method]

            Preventive Measures:
            - [measure]
            """
        )
        from langchain_core.runnables import RunnablePassthrough
        _rag_chain = prompt | _rag_llm | StrOutputParser()
        log.info("✅ Gemini RAG chain ready.")
        return True
    except Exception as e:
        log.error(f"❌ RAG chain setup failed: {e}")
        return False


# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 3 — CORE HELPER FUNCTIONS
# ═════════════════════════════════════════════════════════════════════════════

def _get_best_prediction(results) -> Tuple[str, float]:
    """Extract the highest-confidence class from a YOLO result object."""
    # Classification head (probs)
    if hasattr(results, "probs") and results.probs is not None:
        cls_id = results.probs.top1
        conf   = results.probs.top1conf.item() * 100
        return CLASS_NAMES.get(cls_id, "Unknown"), round(conf, 1)
    # Detection head (boxes)
    if results.boxes and len(results.boxes) > 0:
        best_idx = results.boxes.conf.argmax()
        conf     = results.boxes.conf[best_idx].item() * 100
        cls_id   = int(results.boxes.cls[best_idx].item())
        return CLASS_NAMES.get(cls_id, "Unknown"), round(conf, 1)
    return "No Detection", 0.0


def _resolve_final_prediction(
    cls_v8: str, conf_v8: float,
    cls_v12: str, conf_v12: float,
) -> Tuple[Optional[str], float, str]:
    """
    Apply the ensemble decision logic.
    Returns (final_class | None, best_confidence, status_message).
    """
    HIGH = CONFIDENCE_THRESHOLD

    # Both confident & agree
    if conf_v8 >= HIGH and conf_v12 >= HIGH and cls_v8 == cls_v12:
        return cls_v8, max(conf_v8, conf_v12), "agree_high"

    # Both confident & disagree — take the higher one
    if conf_v8 >= HIGH and conf_v12 >= HIGH and cls_v8 != cls_v12:
        winner = (cls_v8, conf_v8) if conf_v8 >= conf_v12 else (cls_v12, conf_v12)
        return winner[0], winner[1], "disagree_high"

    # Only v8 confident
    if conf_v8 >= HIGH:
        return cls_v8, conf_v8, "single_v8"

    # Only v12 confident
    if conf_v12 >= HIGH:
        return cls_v12, conf_v12, "single_v12"

    # Neither confident
    return None, max(conf_v8, conf_v12), "low_confidence"


def _translate_text(english_text: str, target_lang: str) -> str:
    """
    Translate English text to target_lang using IndicTrans2.
    Falls back to English on any error.
    """
    if target_lang == "English":
        return english_text
    lang_code = INDIC_LANG_CODES.get(target_lang)
    if not lang_code:
        return english_text

    if not _load_indic_model():
        return f"[Translation unavailable — IndicTrans2 not loaded]\n\n{english_text}"

    try:
        batch  = _indic_processor.preprocess_batch(
            [english_text], src_lang="eng_Latn", tgt_lang=lang_code
        )
        inputs = _indic_tokenizer(
            batch, truncation=True, padding="longest",
            return_tensors="pt", return_attention_mask=True
        ).to(DEVICE)
        with torch.no_grad():
            generated = _indic_model.generate(
                **inputs, use_cache=False, min_length=0, max_length=512, num_beams=5
            )
        with _indic_tokenizer.as_target_tokenizer():
            decoded = _indic_tokenizer.batch_decode(
                generated.detach().cpu().tolist(),
                skip_special_tokens=True,
                clean_up_tokenization_spaces=True,
            )
        return _indic_processor.postprocess_batch(decoded, lang=lang_code)[0]
    except Exception as e:
        log.error(f"Translation error: {e}")
        return english_text


def _synthesize_speech(text: str, lang: str) -> Optional[str]:
    """
    Convert text to an MP3 file using edge-tts via subprocess.
    Returns the path to a temporary .mp3 file, or None on failure.
    """
    voice = TTS_VOICES.get(lang, "en-US-JennyNeural")
    try:
        tmp = tempfile.NamedTemporaryFile(suffix=".mp3", delete=False)
        tmp.close()
        result = subprocess.run(
            ["edge-tts", "--voice", voice, "--text", text[:1500], "--write-media", tmp.name],
            capture_output=True, timeout=30
        )
        if result.returncode == 0 and Path(tmp.name).stat().st_size > 0:
            return tmp.name
        log.error(f"edge-tts error: {result.stderr.decode()[:200]}")
        return None
    except Exception as e:
        log.error(f"TTS failed: {e}")
        return None


def _build_raw_predictions_md(cls_v8, conf_v8, cls_v12, conf_v12, lang: str) -> str:
    """Format the raw model output table in Markdown."""
    t = ui_translations.get(lang, ui_translations["English"])
    return (
        f"### {t['raw_predictions']}\n\n"
        f"| Model | Prediction | Confidence |\n"
        f"|-------|-----------|------------|\n"
        f"| 🔷 YOLOv8n  | {cls_v8}  | {conf_v8:.1f}% |\n"
        f"| 🔶 YOLOv12n | {cls_v12} | {conf_v12:.1f}% |\n"
    )


def _get_translated_record(disease_id: str, lang: str) -> dict | None:
    """
    Return the pre-translated record from TRANSLATED_DB cache if available,
    otherwise return None (caller must fall back to live IndicTrans2).
    """
    if _CACHE_LOADED and lang in TRANSLATED_DB:
        return TRANSLATED_DB[lang].get(disease_id)
    return None


def _format_treatment(record: dict, lang: str, disease_id: str = "") -> str:
    """
    Build a plain treatment report from a TREATMENT_DB record.
    Shows only disease/crop name and treatment fields — no bold, no symptoms/pathogen.

    Priority:
      1. TRANSLATED_DB cache (instant, no IndicTrans2 call)
      2. Live IndicTrans2 translation (slow, only if cache absent)
    """
    disease_name = record["disease"]["common_name"]
    crop_name    = record["crop"]["common_name"]

    d_label  = _xt(lang, "disease_label")
    c_label  = _xt(lang, "crop_label")
    chem_lbl = _xt(lang, "chemical_mgmt")
    prev_lbl = _xt(lang, "preventive_measures")

    header = f"{d_label}: {disease_name}  \n{c_label}: {crop_name}\n\n---\n\n"

    if lang == "English":
        chem_list = record["management"]["chemical"]
        prev_list = record["management"]["preventive"]
        body = (
            f"{chem_lbl}:\n\n"
            + "".join(f"- {c}\n" for c in chem_list)
            + f"\n\n{prev_lbl}:\n\n"
            + "".join(f"- {p}\n" for p in prev_list)
        )
        return header + body

    # ── Try pre-translated cache first ───────────────────────────────────────
    cached = _get_translated_record(disease_id, lang) if disease_id else None
    if cached:
        chem_list = cached["management"]["chemical"]
        prev_list = cached["management"]["preventive"]
        body = (
            f"{chem_lbl}:\n\n"
            + "".join(f"- {c}\n" for c in chem_list)
            + f"\n\n{prev_lbl}:\n\n"
            + "".join(f"- {p}\n" for p in prev_list)
        )
        return header + body

    # ── Fallback: live IndicTrans2 translation ────────────────────────────────
    chem_list = record["management"]["chemical"]
    prev_list = record["management"]["preventive"]
    body_en = (
        f"Chemical Management:\n\n"
        + "".join(f"- {c}\n" for c in chem_list)
        + f"\n\nPreventive Measures:\n\n"
        + "".join(f"- {p}\n" for p in prev_list)
    )
    translated = _translate_text(body_en, lang)
    translated = translated.replace("Chemical Management:", f"{chem_lbl}:")
    translated = translated.replace("Preventive Measures:", f"{prev_lbl}:")
    return header + translated


def _format_disease_details(yolo_class: str, lang: str) -> str:
    """Return a Markdown card with taxonomy + symptom info for the detected class."""
    info = disease_info.get(yolo_class, {})
    if not info:
        return "_No detailed taxonomy found for this class._"

    sci_name    = info.get("scientific_name", "N/A")
    common_name = info.get(lang, info.get("English", "N/A"))
    is_healthy  = info.get("is_healthy", False)

    t = ui_translations.get(lang, ui_translations["English"])

    if is_healthy:
        return (
            f"✅ **{t['healthy_message']}**\n\n"
            f"- **{t['scientific_name']}:** *{sci_name}*\n"
            f"- **{t['common_name']}:** {common_name}\n"
        )

    # Get disease_id for richer info
    disease_id  = disease_id_mapping.get(yolo_class)
    record      = TREATMENT_DB.get(disease_id, {}) if disease_id else {}
    pathogen_en = record.get("pathogen_type", "")
    symptoms_en = record.get("symptoms", "Symptom details not available.")

    # Use pre-translated cache when available (avoids IndicTrans2 call)
    cached = _get_translated_record(disease_id, lang) if (disease_id and lang != "English") else None
    if cached:
        pathogen = cached.get("pathogen_type", pathogen_en)
        symptoms = cached.get("symptoms", symptoms_en)
    elif lang != "English":
        pathogen = _translate_text(pathogen_en, lang)
        symptoms = _translate_text(symptoms_en, lang)
    else:
        pathogen = pathogen_en
        symptoms = symptoms_en

    return (
        f"### 🔬 {t['final_analysis']}\n\n"
        f"| {_xt(lang, 'field')} | {_xt(lang, 'detail')} |\n"
        f"|-------|--------|\n"
        f"| {t['scientific_name']} | {sci_name} |\n"
        f"| {t['common_name']} | {common_name} |\n"
        f"| {_xt(lang, 'pathogen_type')} | {pathogen} |\n\n"
        f"**{_xt(lang, 'symptoms')}:**\n\n{symptoms}"
    )


# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 4 — PRIMARY PREDICTION PIPELINE
# ═════════════════════════════════════════════════════════════════════════════

def run_prediction(image: Image.Image, language: str):
    """
    Main pipeline:
    - Load YOLO models (if needed)
    - Resize image to 640×640
    - Run both models and apply ensemble decision logic
    - Return: (annotated_v8, annotated_v12, raw_md, status, final_class, is_low_conf)
    """
    if image is None:
        return None, None, "⚠️ Please upload an image first.", "idle", None, False

    t = ui_translations.get(language, ui_translations["English"])

    if not _load_yolo_models():
        return (
            None, None,
            "❌ YOLO models could not be loaded. Please check model paths in Space settings.",
            "error", None, False
        )

    img_resized = image.resize((640, 640))

    # Run inference
    res_v8  = _yolo_v8(img_resized)[0]
    res_v12 = _yolo_v12(img_resized)[0]

    cls_v8,  conf_v8  = _get_best_prediction(res_v8)
    cls_v12, conf_v12 = _get_best_prediction(res_v12)

    # Annotated images (BGR → RGB)
    try:
        img_ann_v8  = Image.fromarray(res_v8.plot()[..., ::-1])
        img_ann_v12 = Image.fromarray(res_v12.plot()[..., ::-1])
    except Exception:
        img_ann_v8  = img_resized
        img_ann_v12 = img_resized

    # Ensemble decision
    final_class, best_conf, status = _resolve_final_prediction(
        cls_v8, conf_v8, cls_v12, conf_v12
    )

    raw_md = _build_raw_predictions_md(cls_v8, conf_v8, cls_v12, conf_v12, language)

    # ── Status banner ──────────────────────────────────────────────────────
    if status == "agree_high":
        banner = (
            f"✅ **High Confidence Agreement** — Both models agree: "
            f"**{final_class}** ({best_conf:.1f}%)"
        )
    elif status == "disagree_high":
        banner = (
            f"⚠️ **Models Disagree** — Both confident but differ. "
            f"Using higher-confidence result: **{final_class}** ({best_conf:.1f}%). "
            f"Manual verification recommended."
        )
    elif status == "single_v8":
        banner = (
            f"🔍 **Single Model Result** — YOLOv8n is confident: "
            f"**{final_class}** ({best_conf:.1f}%). YOLOv12n was uncertain."
        )
    elif status == "single_v12":
        banner = (
            f"🔍 **Single Model Result** — YOLOv12n is confident: "
            f"**{final_class}** ({best_conf:.1f}%). YOLOv8n was uncertain."
        )
    else:  # low_confidence
        banner = (
            f"❌ **Low Confidence** — Neither model exceeded {CONFIDENCE_THRESHOLD}%. "
            f"Best guesses: {cls_v8} ({conf_v8:.1f}%) & {cls_v12} ({conf_v12:.1f}%). "
            f"Please describe symptoms below for AI-assisted diagnosis."
        )

    is_low_conf = (final_class is None)
    return img_ann_v8, img_ann_v12, raw_md + "\n" + banner, status, final_class, is_low_conf


# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 5 — SHOW DISEASE DETAILS
# ═════════════════════════════════════════════════════════════════════════════

def show_disease_details(final_class: Optional[str], language: str):
    if not final_class:
        return "No confirmed detection to display details for.", None
    details_md  = _format_disease_details(final_class, language)
    audio_path  = _synthesize_speech(_plain_text(details_md), language)
    return details_md, audio_path


def _plain_text(md: str) -> str:
    """Strip Markdown for TTS."""
    import re
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", md)
    text = re.sub(r"\*(.+?)\*",     r"\1", text)
    text = re.sub(r"`(.+?)`",       r"\1", text)
    text = re.sub(r"#+\s*",         "",    text)
    text = re.sub(r"\|.*?\|",       " ",   text)
    text = re.sub(r"-{2,}",         "",    text)
    text = re.sub(r"\n{2,}",        "\n",  text)
    return text.strip()


# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 6 — SHOW TREATMENT
# ═════════════════════════════════════════════════════════════════════════════

def show_treatment(final_class: Optional[str], language: str):
    if not final_class:
        return "No confirmed detection to look up treatment for.", None

    disease_id = disease_id_mapping.get(final_class)

    # Healthy plant — no treatment
    info = disease_info.get(final_class, {})
    if info.get("is_healthy"):
        t   = ui_translations.get(language, ui_translations["English"])
        msg = t.get("healthy_message", "This plant appears healthy. No treatment needed!")
        return msg, _synthesize_speech(msg, language)

    if not disease_id or disease_id not in TREATMENT_DB:
        return (
            f"⚠️ Treatment protocol not found for `{final_class}` in local database. "
            f"Please use the symptom-based search below.",
            None
        )

    record   = TREATMENT_DB[disease_id]
    treat_md = _format_treatment(record, language, disease_id=disease_id)
    audio    = _synthesize_speech(_plain_text(treat_md), language)
    return treat_md, audio


# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 7 — SYMPTOM-BASED FALLBACK (RAG)
# ═════════════════════════════════════════════════════════════════════════════

def search_by_symptoms(crop_name: str, symptoms_text: str, language: str):
    if not crop_name.strip() or not symptoms_text.strip():
        return "⚠️ Please enter both a crop name and a symptom description.", None

    if not _load_rag_chain():
        # Attempt local keyword matching as a fallback
        return _local_symptom_match(crop_name, symptoms_text, language)

    try:
        english_result = _rag_chain.invoke({
            "crop": crop_name,
            "symptoms": symptoms_text,
        })
    except Exception as e:
        log.error(f"RAG chain error: {e}")
        return _local_symptom_match(crop_name, symptoms_text, language)

    # Strip any residual markdown Gemini added (bold, italic, headers)
    import re
    english_clean = re.sub(r"\*{1,3}(.+?)\*{1,3}", r"\1", english_result)
    english_clean = re.sub(r"^#{1,3}\s*", "", english_clean, flags=re.MULTILINE)
    english_clean = re.sub(r"^\d+\.\s*", "- ", english_clean, flags=re.MULTILINE)

    # Translate output if needed
    final_text = _translate_text(english_clean, language) if language != "English" else english_clean
    audio      = _synthesize_speech(_plain_text(final_text), language)
    return final_text, audio


def _local_symptom_match(crop_name: str, symptoms_text: str, language: str) -> Tuple[str, None]:
    """
    Keyword-based fallback when Gemini RAG is unavailable.
    Accepts input in any language — translates to English first for keyword matching.
    """
    # Translate user input to English for matching if not already English
    query_en = _translate_text(symptoms_text, "English") if language != "English" else symptoms_text
    # Also keep original words as fallback (catches Hinglish / English mixed input)
    query_words = set(query_en.lower().split()) | set(symptoms_text.lower().split())
    crop_lower  = crop_name.lower()
    best_match  = None
    best_score  = 0

    best_disease_id = ""
    for disease_id, record in TREATMENT_DB.items():
        crop_match = crop_lower in record["crop"]["common_name"].lower()
        if not crop_match:
            continue
        symptom_words = set(record.get("symptoms", "").lower().split())
        score = len(query_words & symptom_words)
        if score > best_score:
            best_score      = score
            best_match      = record
            best_disease_id = disease_id

    if best_match:
        label = _xt(language, "best_local_match")
        treatment = _format_treatment(best_match, language, disease_id=best_disease_id)
        result = f"{label}\n\n{treatment}"
    else:
        result = _xt(language, "no_match")
    audio = _synthesize_speech(_plain_text(result), language)
    return result, audio


# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 8 — CROP LIST FOR FALLBACK DROPDOWN
# ═════════════════════════════════════════════════════════════════════════════
CROP_CHOICES = ["Apple", "Maize / Corn", "Grape", "Potato", "Tomato"]


# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 9 — GRADIO UI
# ═════════════════════════════════════════════════════════════════════════════

CSS = """
/* ── Global ── */
body { font-family: 'Segoe UI', sans-serif; }
.gradio-container { max-width: 1100px !important; margin: auto; }

/* ── Header ── */
#app-header { text-align: center; padding: 24px 0 8px; }
#app-header h1 { font-size: 2rem; font-weight: 700;
    background: linear-gradient(90deg, #16a34a, #15803d);
    -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
#app-header p  { color: #555; font-size: 1rem; margin-top: 4px; }

/* ── Panels ── */
.panel-card { border: 1px solid #e2e8f0; border-radius: 12px;
    padding: 16px; background: #f8fafc; margin-top: 8px;
    color: #1a1a1a !important; }
.panel-card p, .panel-card table, .panel-card td, .panel-card th,
.panel-card li, .panel-card h1, .panel-card h2, .panel-card h3,
.panel-card span, .panel-card strong, .panel-card em, .panel-card code {
    color: #1a1a1a !important; }
/* Raw predictions — force entire markdown block dark */
#raw-pred-box, #raw-pred-box * {
    color: #1a1a1a !important; }
#raw-pred-box code {
    background: #e2e8f0 !important;
    color: #1a1a1a !important;
    border-radius: 4px; padding: 1px 5px; }

/* ── Buttons ── */
#predict-btn  { background: #16a34a !important; color: white !important; font-size: 1rem; }
#disease-btn  { background: #0ea5e9 !important; color: white !important; }
#treatment-btn{ background: #f59e0b !important; color: white !important; }
#symptom-btn  { background: #8b5cf6 !important; color: white !important; }
button:hover  { opacity: 0.88; transition: opacity 0.15s; }

/* ── Confidence badge ── */
.low-conf-panel { border-color: #f87171 !important; background: #fff1f2 !important; }
"""

THEME = gr.themes.Soft(
    primary_hue="green",
    secondary_hue="blue",
    neutral_hue="slate",
)


def build_ui():
    with gr.Blocks(theme=THEME, css=CSS, title="Plant Disease Detector") as demo:

        # ── Internal state ──────────────────────────────────────────────────
        state_lang        = gr.State("English")
        state_final_class = gr.State(None)     # confirmed YOLO class string
        state_is_low_conf = gr.State(False)

        # ═══════════════════════════════════════════════════════════════════
        #  HEADER
        # ═══════════════════════════════════════════════════════════════════
        with gr.Row(elem_id="app-header"):
            with gr.Column():
                app_title    = gr.Markdown("# 🌿 Plant Disease Detection")
                app_subtitle = gr.Markdown(
                    "Upload a leaf image to detect diseases and get treatment recommendations."
                )

        # ═══════════════════════════════════════════════════════════════════
        #  ROW 1 — Language selector
        # ═══════════════════════════════════════════════════════════════════
        with gr.Row():
            with gr.Column(scale=1):
                lang_dd = gr.Dropdown(
                    choices=["English", "Hindi", "Urdu", "Telugu"],
                    value="English",
                    label="🌐 Select Language / भाषा चुनें / زبان منتخب کریں / భాష ఎంచుకోండి",
                    interactive=True,
                )

        # ═══════════════════════════════════════════════════════════════════
        #  ROW 2 — Image upload + annotated outputs
        # ═══════════════════════════════════════════════════════════════════
        with gr.Row():
            with gr.Column(scale=1):
                img_input = gr.Image(
                    type="pil",
                    label="📷 Upload Plant Leaf Image",
                    elem_classes="panel-card",
                    height=300,
                )
                predict_btn = gr.Button(
                    "🔍 Predict Disease", variant="primary",
                    elem_id="predict-btn", size="lg"
                )

            with gr.Column(scale=2):
                with gr.Row():
                    out_v8  = gr.Image(label="YOLOv8n Detections",  height=240)
                    out_v12 = gr.Image(label="YOLOv12n Detections", height=240)

        # ═══════════════════════════════════════════════════════════════════
        #  ROW 3 — Raw predictions + Status banner
        # ═══════════════════════════════════════════════════════════════════
        with gr.Row():
            raw_pred_md = gr.Markdown(
                value="*Results will appear here after prediction…*",
                elem_classes="panel-card",
                elem_id="raw-pred-box",
            )

        # ═══════════════════════════════════════════════════════════════════
        #  ROW 4 — Disease Details + Treatment (on-demand)
        # ═══════════════════════════════════════════════════════════════════
        with gr.Row(visible=True) as details_row:
            with gr.Column():
                with gr.Accordion("🔬 Disease Details", open=False) as acc_details:
                    disease_btn = gr.Button(
                        "Show Disease Details", elem_id="disease-btn"
                    )
                    details_md  = gr.Markdown("*Click the button above to load details.*")
                    details_audio = gr.Audio(
                        label="🔊 Listen", autoplay=False, visible=True
                    )

            with gr.Column():
                with gr.Accordion("💊 Treatment Recommendations", open=False) as acc_treatment:
                    treatment_btn = gr.Button(
                        "Show Treatment Plan", elem_id="treatment-btn"
                    )
                    treatment_md  = gr.Markdown("*Click the button above to load treatment.*")
                    treatment_audio = gr.Audio(
                        label="🔊 Listen", autoplay=False, visible=True
                    )

        # ═══════════════════════════════════════════════════════════════════
        #  ROW 5 — Symptom-based fallback (shown on low confidence)
        # ═══════════════════════════════════════════════════════════════════
        with gr.Row(visible=False) as fallback_row:
            with gr.Column():
                gr.Markdown(
                    "### ❓ Low Confidence — Describe Symptoms for AI Diagnosis",
                    elem_classes="panel-card"
                )
                with gr.Row():
                    crop_dd = gr.Dropdown(
                        choices=CROP_CHOICES,
                        label="🌾 Crop Name",
                        value="Tomato",
                        interactive=True,
                    )
                    symptom_tb = gr.Textbox(
                        label="📝 Describe Symptoms",
                        placeholder=_xt("English", "symptom_placeholder"),
                        lines=3,
                    )
                symptom_btn = gr.Button(
                    "🔎 Search by Symptoms (AI)", elem_id="symptom-btn"
                )
                symptom_md    = gr.Markdown("*Symptom analysis results will appear here.*")
                symptom_audio = gr.Audio(label="🔊 Listen", autoplay=False)

        # ═══════════════════════════════════════════════════════════════════
        #  FOOTER
        # ═══════════════════════════════════════════════════════════════════
        gr.Markdown(
            "---\n"
            "**Data Sources:** ICAR, TNAU, KVK, UC IPM, CABI  |  "
            "**Models:** YOLOv8n & YOLOv12n fine-tuned on 28-class plant disease dataset  |  "
            "**Translation:** IndicTrans2 (AI4Bharat)  |  "
            "**RAG LLM:** Google Gemini 2.0 Flash"
        )

        # ═══════════════════════════════════════════════════════════════════
        #  EVENT WIRING
        # ═══════════════════════════════════════════════════════════════════

        # ── Language selector updates UI labels ───────────────────────────
        def update_language_labels(lang):
            t = ui_translations.get(lang, ui_translations["English"])
            return (
                gr.update(label=f"📷 {t['upload_image']}"),
                gr.update(value=f"🔍 {t['predict_btn']}"),
                gr.update(value=f"Show {t['show_disease_details']}"),
                gr.update(value=f"Show {t['show_treatment']}"),
                gr.update(label=t["crop_name_fallback"]),
                gr.update(label=t["symptoms_fallback"], placeholder=_xt(lang, "symptom_placeholder")),
                gr.update(value=f"🔎 {t['search_fallback_btn']}"),
                lang,   # update state
            )

        lang_dd.change(
            fn=update_language_labels,
            inputs=[lang_dd],
            outputs=[
                img_input, predict_btn,
                disease_btn, treatment_btn,
                crop_dd, symptom_tb, symptom_btn,
                state_lang,
            ],
        )

        # ── Predict button ────────────────────────────────────────────────
        def on_predict(image, language):
            img_v8, img_v12, raw_md, status, final_class, is_low_conf = run_prediction(
                image, language
            )
            show_fallback = gr.update(visible=is_low_conf)
            show_details  = gr.update(visible=not is_low_conf)
            return (
                img_v8, img_v12, raw_md,
                final_class, is_low_conf,
                show_fallback, show_details,
            )

        predict_btn.click(
            fn=on_predict,
            inputs=[img_input, state_lang],
            outputs=[
                out_v8, out_v12, raw_pred_md,
                state_final_class, state_is_low_conf,
                fallback_row, details_row,
            ],
        )

        # ── Disease details button ─────────────────────────────────────────
        disease_btn.click(
            fn=show_disease_details,
            inputs=[state_final_class, state_lang],
            outputs=[details_md, details_audio],
        )

        # ── Treatment button ───────────────────────────────────────────────
        treatment_btn.click(
            fn=show_treatment,
            inputs=[state_final_class, state_lang],
            outputs=[treatment_md, treatment_audio],
        )

        # ── Symptom search button ─────────────────────────────────────────
        symptom_btn.click(
            fn=search_by_symptoms,
            inputs=[crop_dd, symptom_tb, state_lang],
            outputs=[symptom_md, symptom_audio],
        )

    return demo


# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 10 — ENTRY POINT
# ═════════════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    # Pre-warm YOLO models at startup (non-blocking on error)
    log.info("Pre-warming YOLO models…")
    _load_yolo_models()

    demo = build_ui()
    demo.queue(max_size=10).launch(
        server_name="0.0.0.0",
        server_port=7860,
        share=False,
        show_error=True,
    )
